global:
  image:
    registry: 172.30.1.1:5000

rbac:
  roleBindings: 
    - name: "admin"

images:
  os: ""

master:
  image: "jenkins-openshift"
  imageTag: "v3.11"
  build:
    git:
      uri: "https://github.com/arnaud-deprez/jenkins-openshift-docker.git"
    contextDir: "2"
agent:
  enabled: true
  podTemplates:
    jnlp:
      containers:
        jnlp:
          image: "jenkins-jnlp"
          imageTag: "v3.11"
          build:
            git:
              uri: "https://github.com/arnaud-deprez/jenkins-openshift-docker.git"
            contextDir: "jnlp"
    base:
      containers:
        base:
          image: "jenkins-builder-base"
          imageTag: "v3.11"
          build:
            git:
              uri: "https://github.com/arnaud-deprez/jenkins-openshift-docker.git"
            contextDir: "builder-base"
    gradle:
      containers:
        gradle:
          image: "jenkins-builder-gradle"
          imageTag: "v3.11"
          build:
            git:
              uri: "https://github.com/arnaud-deprez/jenkins-openshift-docker.git"
            contextDir: "builder-gradle"
            from:
              kind: ImageStreamTag
              name: "jenkins-builder-base"
              tag: "v3.11"
    nodejs:
      containers:
        nodejs:
          image: "jenkins-builder-nodejs"
          imageTag: "v3.11"
          build:
            git:
              uri: "https://github.com/arnaud-deprez/jenkins-openshift-docker.git"
            contextDir: "builder-nodejs"
            from:
              kind: ImageStreamTag
              name: "jenkins-builder-base"
              tag: "v3.11"
