sudo: required

services:
  - docker

env:
  - PATH="$PATH:/tmp/bin"
  
install: "ci/install.sh"

stages:
  - "build base"
  - "build builders"

jobs:
  include:
    # branch != master
    - stage: "build base"
      name: "master"
      script: make -C 2 test
      if: branch != master
    - stage: "build base"
      name: "jnlp agent"
      script: make -C jnlp test
      if: branch != master
    - stage: "build base"
      name: "base builder"
      script: make -C builder-base test
      if: branch != master
    
    - stage: "build builders"
      name: "gradle agent"
      script: make -C builder-gradle test
      if: branch != master
    - stage: "build builders"
      name: "nodejs agent"
      script: make -C builder-nodejs test
      if: branch != master

  # branch = master
    - stage: "build base"
      name: "master"
      script: make -C 2 publish
      if: branch = master
    - stage: "build base"
      name: "jnlp agent"
      script: make -C jnlp publish
      if: branch = master
    - stage: "build base"
      name: "base builder"
      script: make -C builder-base publish
      if: branch = master
    
    - stage: "build builders"
      name: "gradle agent"
      script: make -C builder-gradle publish
      if: branch = master
    - stage: "build builders"
      name: "nodejs agent"
      script: make -C builder-nodejs publish
      if: branch = master