sudo: required

services:
  - docker

stages:
  - "build base"
  - "build agents"

jobs:
  include:
    # branch != master
    - stage: "build base"
      name: "master"
      script: make -C 2 test
      if: branch != master
    - stage: "build base"
      name: "jnlp agent"
      script: make -C jnlp test
      if: branch != master
    - stage: "build base"
      name: "base agent"
      script: make -C agent-base test
      if: branch != master
    
    - stage: "build agents"
      name: "gradle agent"
      script: make -C agent-gradle test
      if: branch != master
    - stage: "build agents"
      name: "nodejs agent"
      script: make -C agent-nodejs test
      if: branch != master

  # branch = master
    - stage: "build base"
      name: "master"
      script: make -C 2 publish
      if: branch = master
    - stage: "build base"
      name: "jnlp agent"
      script: make -C jnlp publish
      if: branch = master
    - stage: "build base"
      name: "base agent"
      script: make -C agent-base publish
      if: branch = master
    
    - stage: "build agents"
      name: "gradle agent"
      script: make -C agent-gradle publish
      if: branch = master
    - stage: "build agents"
      name: "nodejs agent"
      script: make -C agent-nodejs publish
      if: branch = master