{{- if .Values.agent.enabled -}}
apiVersion: v1
kind: List
items:
  {{- $root := . -}}
  {{- range $pkey, $pval := .Values.agent.podTemplates -}}
  {{- range $ckey, $cval := $pval.containers -}}
  {{- if $cval.build }}
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      labels:
        {{- include "jenkins-openshift.labels" $root | nindent 8 }}
        build: jenkins
        image: {{ $ckey | lower | quote }}
      name: {{ regexSplit "/" $cval.image -1 | last }}
    spec:
      failedBuildsHistoryLimit: 1
      successfulBuildsHistoryLimit: 1
      output:
        to:
          kind: ImageStreamTag
          name: "{{ regexSplit "/" $cval.image -1 | last }}:{{ default "latest" $cval.imageTag }}"
      postCommit: {}
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 1000m
          memory: 512Mi
      runPolicy: Serial
      source:
        type: Git
        git:
          uri: {{ $cval.build.git.uri | quote }}
          ref: {{ default "master" $cval.build.git.ref | quote }}
        contextDir: {{ $cval.build.contextDir | quote }}
      strategy:
        dockerStrategy:
          {{- if $cval.build.from }}
          from:
            kind: {{ $cval.build.from.kind | quote }}
            name: "{{ $cval.build.from.name }}:{{ default "latest" $cval.build.from.tag }}"
          {{- end }}
          {{- if $cval.build.env }}
          env:
            {{- range $ekey, $eval := $cval.build.env }}
            - name: {{ $ekey | quote }}
              value: {{ $eval | quote }}
            {{- end }}
          {{- end }}
          noCache: true
          forcePull: true
          {{- if $root.Values.images.os }}
          dockerfilePath: "Dockerfile.{{ $root.Values.images.os }}"
          {{- end }}
        type: Docker
      triggers: {{ if not $cval.build.triggers }}[]{{- else -}}
        {{- range $index, $trigger := $cval.build.triggers }}
        - type: {{ $trigger.type | quote }}
          {{- if eq "ImageChange" $trigger.type }}
          imageChange: {{ if not $trigger.from }}{}{{- else -}}
            from:
              kind: {{ $trigger.from.kind | quote }}
              name: "{{ $trigger.from.name }}:{{ default "latest" $trigger.from.tag }}"
            {{- end -}}
          {{- end -}}
        {{- end }}
      {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}