apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    {{- include "jenkins-openshift.labels" . | nindent 4 }}
    build: jenkins
  name: {{ regexSplit "/" .Values.master.image -1 | last }}
spec: {}