apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    {{- include "jenkins-openshift.labels" . | nindent 4 }}
    build: jenkins
  name: {{ regexSplit "/" .Values.master.image -1 | last }}
spec:
  failedBuildsHistoryLimit: 1
  successfulBuildsHistoryLimit: 1
  output:
    to:
      kind: ImageStreamTag
      name: "{{ regexSplit "/" .Values.master.image -1 | last }}:{{ .Values.master.imageTag }}"
  postCommit: {}
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 1000m
      memory: 512Mi
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: {{ .Values.master.build.git.uri | quote }}
      ref: {{ default "master" .Values.master.build.git.ref | quote }}
    contextDir: {{ .Values.master.build.contextDir | quote }}
  strategy:
    dockerStrategy:
    {{- if .Values.master.build.env }}
      env:
      {{- range $ekey, $eval := .Values.master.build.env }}
        - name: {{ $ekey | quote }}
          value: {{ $eval | quote }}
      {{- end }}
    {{- end }}
      noCache: true
      forcePull: true
      {{- if .Values.images.os }}
      dockerfilePath: Dockerfile.{{ .Values.images.os }}
      {{- end }}
    type: Docker
  triggers: []