apiVersion: template.openshift.io/v1
kind: Template
metadata:
  labels:
    template: jenkins-agent-gradle-nodejs-template
    role: jenkins-slave
  name: jenkins-agent-gradle-nodejs
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      role: jenkins-slave
    name: jenkins-agent-gradle-nodejs
  data:
    gradle-nodejs: |-
      <org.csanchez.jenkins.plugins.kubernetes.PodTemplate>
        <inheritFrom>gradle nodejs</inheritFrom>
        <name>gradle-nodejs</name>
        <instanceCap>10</instanceCap>
        <idleMinutes>15</idleMinutes>
        <label>gradle-nodejs</label>
        <serviceAccount>jenkins</serviceAccount>
        <nodeSelector></nodeSelector>
        <volumes/>
        <containers/>
        <envVars/>
        <annotations/>
        <imagePullSecrets/>
        <nodeProperties/>
      </org.csanchez.jenkins.plugins.kubernetes.PodTemplate>
parameters: []