apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "jenkins-openshift.fullname" . }}
  labels:
    {{- include "jenkins-openshift.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "jenkins-openshift.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        # trick to trigger app to restart if ConfigMap have changed
        # https://helm.sh/docs/developing_charts/#automatically-roll-deployments-when-configmaps-or-secrets-change
        checksum/jenkins-casc-configmap: {{ include (print $.Template.BasePath "/jenkins-casc-configmap.yaml") . | sha256sum }}
      labels:
        {{- include "jenkins-openshift.labels" . | nindent 8 }}
    spec:
      {{- if .Values.master.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.master.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.master.tolerations }}
      tolerations:
        {{- toYaml .Values.master.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.master.affinity }}
      affinity:
        {{- toYaml .Values.master.affinity | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ if .Values.rbac.create }}{{ default "default" .Values.rbac.serviceAccount.name }}{{ end }}
      containers:
      - name: "jenkins"
        image: "{{ .Values.global.image.registry }}/{{ .Values.master.image }}:{{ .Values.master.imageTag }}"
        imagePullPolicy: "{{ .Values.master.imagePullPolicy }}"
        env:
        - name: OPENSHIFT_ENABLE_OAUTH
          value: {{ .Values.master.oauth.enabled | quote }}
        - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
          value: "true"
        - name: KUBERNETES_MASTER
          value: https://kubernetes.default:443
        - name: KUBERNETES_TRUST_CERTIFICATES
          value: "true"
        - name: JENKINS_SERVICE_NAME
          value: {{ template "jenkins-openshift.fullname" . }}
        - name: JNLP_SERVICE_NAME
          value: {{ template "jenkins-openshift.fullname" . }}-agent
        - name: OVERRIDE_PV_CONFIG_WITH_IMAGE_CONFIG
          value: {{ .Values.master.overwrite.config | quote }}
        - name: OVERRIDE_PV_PLUGINS_WITH_IMAGE_PLUGINS
          value: {{ .Values.master.overwrite.plugins | quote }}
        {{- if .Values.master.env }}
        {{- range $ekey, $eval := .Values.master.env }}
        - name: {{ $ekey | quote }}
          value: {{ $eval | quote }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.master.containerPort }}
          name: http
        - containerPort: {{ .Values.master.slaveListenerPort }}
          name: slavelistener
        {{- if .Values.master.jmxPort }}
        - containerPort: {{ .Values.master.jmxPort }}
          name: jmx
        {{- end }}
        {{- if .Values.master.healthProbes }}
        livenessProbe:
          httpGet:
            path: /login
            port: http
          initialDelaySeconds: {{ .Values.master.healthProbes.liveness.initialDelay }}
          timeoutSeconds: {{ .Values.master.healthProbes.liveness.timeout }}
          failureThreshold: {{ .Values.master.healthProbes.liveness.failureThreshold }}
        readinessProbe:
          httpGet:
            path: /login
            port: http
          initialDelaySeconds: {{ .Values.master.healthProbes.readiness.timeout }}
          timeoutSeconds: {{ .Values.master.healthProbes.readiness.timeout }}
          failureThreshold: {{ .Values.master.healthProbes.readiness.failureThreshold }}
        {{- end }}
        resources:
          requests:
            cpu: "{{ .Values.master.cpu }}"
            memory: "{{ .Values.master.memory }}"
        volumeMounts:
        {{- if .Values.master.persistence.mounts }}
        {{- toYaml .Values.master.persistence.mounts | nindent 8 }}
        {{- end -}}
        - mountPath: /var/lib/jenkins
          name: jenkins-home
          readOnly: false
      volumes:
      {{- if .Values.master.persistence.volumes }}
      {{- toYaml .Values.master.persistence.volumes | nindent 6 }}
      {{- end -}}
      - name: jenkins-home
      {{- if .Values.master.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.master.persistence.existingClaim | default (include "jenkins-openshift.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
      {{- if .Values.master.imagePullSecret -}}
      imagePullSecrets:
      - name: {{ .Values.master.imagePullSecret }}
      {{- end }}