{{- if .Values.agent.enabled -}}
{{- $root := . -}}
kind: List
apiVersion: v1
items: 
{{- $noVolume := true -}}
{{- range $pkey, $pval := .Values.agent.podTemplates -}}
{{- range $index, $pvolume := $pval.volumes -}}
{{- if eq "PersistentVolumeClaim" $pvolume.type }}
{{- $noVolume = false -}}
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    {{- if $pvolume.annotations }}
    annotations:
      {{- toYaml $pvolume.annotations | nindent 6 }}
    {{- end }}
    labels:
      {{- include "jenkins-openshift.labels" $root | nindent 6 }}
      role: jenkins-agent
      slave: {{ $pval.name }}
    name: "{{ $pvolume.claimName }}"      
  spec:
    accessModes:
    - {{ $pvolume.accessMode | quote }}
    resources:
      requests:
        storage: {{ $pvolume.size | quote }}
    {{- if $pvolume.storageClass }}
    {{- if (eq "-" $pvolume.storageClass) }}
    storageClassName: ""
    {{- else }}
    storageClassName: "{{ $pvolume.storageClass }}"
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- if $noVolume }}
  []
{{- end }}
{{- end }}