{{- if and .Values.master.persistence.enabled (not .Values.master.persistence.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  {{- if .Values.master.persistence.annotations }}
  annotations:
    {{- toYaml .Values.master.persistence.annotations | nindent 4 }}
  {{- end }}
  name: {{ template "jenkins-openshift.fullname" . }}
  labels:
    {{- include "jenkins-openshift.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.master.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.master.persistence.size | quote }}
  {{- if .Values.master.persistence.storageClass }}
  {{- if (eq "-" .Values.master.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.master.persistence.storageClass }}"
  {{- end }}
  {{- end }}
{{- end }}