{{- if .Values.master.hostName -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    {{- include "jenkins-openshift.labels" . | nindent 4 }}
  annotations:
    template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
    {{- if .Values.master.ingress.annotations }}
    {{- toYaml .Values.master.ingress.annotations | nindent 4 }}
    {{- end }}
  name: {{ template "jenkins-openshift.fullname" . }}
spec:
  rules:
  - host: {{ .Values.master.hostName | quote }}
    http:
      paths:
      - backend:
          serviceName: {{ template "jenkins-openshift.fullname" . }}
          servicePort: {{ .Values.master.servicePort }}
  {{- if .Values.master.ingress.tls }}
  tls:
    {{- toYaml .Values.master.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}