{{- if and .Values.master.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- include "jenkins-openshift.labels" . | nindent 4 }}
  annotations:
    template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
    {{- if .Values.master.route.annotations }}
    {{- toYaml .Values.master.route.annotations | nindent 4 }}
    {{- end }}
  name: {{ template "jenkins-openshift.fullname" . }}
spec:
  tls:
    {{- toYaml .Values.master.route.tls | nindent 4 }}
  to:
    kind: Service
    name: {{ template "jenkins-openshift.fullname" . }}
{{- end }}