{{- if .Values.rbac.create -}}
{{- $serviceName := default "default" .Values.rbac.serviceAccount.name -}}
apiVersion: v1
kind: List
items:
{{- $root := . -}}
  {{- range $index, $pbindings := .Values.rbac.roleBindings }}
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: {{ default "RoleBinding" $pbindings.kind }}
    metadata:
      labels:
        {{- include "jenkins-openshift.labels" $root | nindent 8 }}
      name: "{{ $serviceName }}_{{ $pbindings.name }}"
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: {{ default "ClusterRole" $pbindings.roleKind }}
      name: {{ $pbindings.name }}
    subjects:
    - kind: ServiceAccount
      name: {{ $serviceName }}
      namespace: {{ $root.Release.Namespace }}
  {{- end }}
{{- end }}