{{- if .Values.rbac.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.jenkins: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{template "jenkins-openshift.fullname" .}}"}}'
    {{- if .Values.rbac.serviceAccount.annotations }}
    {{- toYaml .Values.rbac.serviceAccount.annotations | nindent 4 }}
    {{- end }}
  name: {{ .Values.rbac.serviceAccount.name }}
  labels:
    {{- include "jenkins-openshift.labels" . | nindent 4 }}
{{- end }}