kind: "BuildConfig"
apiVersion: "build.openshift.io/v1"
metadata:
  labels:
    build: jenkins
    strategy: pipeline
    app: jenkins-agent-test
  name: "jenkins-test-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        pipeline { 
          agent none 
          stages {
            stage('test base') {
              agent { label 'base' } 
              steps {
                container('base') {
                  echo 'Hello from base slave'
                  sh '/home/jenkins/test/run'
                }
              }
            }
            stage('test gradle') {
              agent { label 'gradle' } 
              steps {
                container('gradle') {
                  echo 'Hello from gradle slave'
                  sh '/home/jenkins/test/run'
                }
              }
            }
            stage('test nodejs') {
              agent { label 'nodejs' }
              steps {
                container('nodejs') {
                  echo 'Hello from nodejs slave'
                  sh '/home/jenkins/test/run'
                }
              }
            }
            stage('test gradle-nodejs') {
              agent { label 'gradle-nodejs' }
              steps {
                echo 'Hello from gradle-nodejs slave'
                container('gradle') {
                  echo 'In container gradle...'
                  sh '/home/jenkins/test/run'
                }
                container('nodejs') {
                  echo 'In container nodejs...'
                  sh '/home/jenkins/test/run'
                }
              }
            }
          }
        }